### ISSUE TITLE
CheckProjectCompiles.vbs "Wrong number of arguments or invalid property assignment:'StdErr'

### ISSUE THREAD

**Issue by Barleyman** [mbedded-ninja/AltiumScriptCentral#173]
As it says. This happens running main.vbs. 14.1. v22.3.2.0. Both Altium v14 and v15 suffer of both problems. 

![altiumscript](https://cloud.githubusercontent.com/assets/693392/5762014/25c62152-9cd7-11e4-8b83-2376e481278b.jpg)

After that the menu comes up and I reselect the footprint I was working on and select "renumber pads" and boom, exceoption in scriptingsystem.dll.dll

![image](https://cloud.githubusercontent.com/assets/693392/5762005/1d9a4e22-9cd7-11e4-87e6-c56aa24c6409.png)

Perhaps I'm just being stupid and don't understand the correct procedure. Open project, run script and pick "main"..

**Comment by gbmhunter** [comment]
Thanks for noting! Your doing things correctly, this I my fault, and it should be fixed in the latest version (v22.3.4.0). Let me know if this works for you and then this issue can be closed.

**Comment by gbmhunter** [comment]
Fixed.
