### ISSUE TITLE
Wrong number of arguments or invalid property assignment: 'StdErr'

### ISSUE THREAD

**Issue by Barleyman** [mbedded-ninja/AltiumScriptCentral#177]
This happens with 22.4.5.0 running main. It appears to occur when you have schematic sheet open when running the script, not if you have offending script file open..

PowerPortChecker.vbs
line
                        Call StdErr("ERROR: Power bar '" + powerObj.Text + "' with incorrect orientation on sheet " + document.DM_FullPath + " found." + VbCr + VbLf)                 

![image](https://cloud.githubusercontent.com/assets/693392/5878672/95d3e71e-a320-11e4-8be3-0288b2496e62.png)

**Comment by gbmhunter** [comment]
Ahh thanks yes I know what will be causing this. Fixing now...
