### ISSUE TITLE
Error: Need object Board. Line 131 in file DrawPolygon.vbs

### ISSUE THREAD

**Issue by sledgeh** [mbedded-ninja/AltiumScriptCentral#203]
Error: Need object Board. Line 131 in file DrawPolygon.vbs
![default](https://cloud.githubusercontent.com/assets/13828976/9980927/87a87c62-5fb4-11e5-9994-0fce43077b5e.PNG)
This error appears only when calling script directly, passing Main. So launch script through Main dialog works normally. Why?

**Comment by gbmhunter** [comment]
Main might be loading the board object into memory before calling this script. I will look into it...

**Comment by gbmhunter** [comment]
It works through main because main calls `DrawPolygon(dummyVar)` which sets up the board object. Calling the script directly doesn't do this. This is intended behaviour.
